### ISSUE TITLE
hypre: libgcc_s.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by davydden** [Homebrew/linuxbrew#366]
In a stand-alone version with OpenSuse I have some issues running tests `hypre` via `brew install hypre --with-mpi --with-openblas`. 
In particular, `libgcc_s.so.1` can't be found:
```
mpiexec -np 2 ./ex1
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
[warn] Epoll ADD(4) on fd 2 failed.  Old events were 0; read change was 0 (none); write change was 1 (add): Operation not permitted
./ex1: error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory
```

However, it is there in the `lib` folder:
```
.linuxbrew/lib> ls | grep libgcc_s.so.1
libgcc_s.so.1
```

There are no issues on Ubuntu non-standalone linuxbrew, so I suppose it is related to stand-alone version...
Any ideas, advices?

**Comment by saketkc** [comment]
Wild guess, but you might want to check if setting `LD_LIBRARY_PATH` helps(I don't think this is recommended though)
https://github.com/Homebrew/linuxbrew/issues/150

**Comment by davydden** [comment]
i see, thanks for the link! 
i guess this could be fixed in `hypre`, but i have no idea how :(

**Comment by davydden** [comment]
funny enough, `brew install sundials --with-mpi` which also run tests
 ```
==> mpiexec -np 4 ./idas/parallel/idasHeat2D_FSA_kry_bbd_p -sensi stg t 
```
is perfectly fine without `LD_LIBRARY_PATH`...

**Comment by saketkc** [comment]
This is because they build `mpi` differently:

https://github.com/Homebrew/homebrew-science/blob/master/sundials.rb#L58

https://github.com/Homebrew/homebrew-science/blob/master/hypre.rb#L81

I am guessing, https://github.com/Homebrew/homebrew-science/blob/master/hypre.rb#L83 does not pickup your `ENV.CXX` to the linuxbrew specific `gcc`(Again, wild guess)

**Comment by sjackman** [comment]
As a workaround disable the tests, and check that it works after building.
`brew install hypre --with-mpi --with-openblas --without-check`

I'm afraid that I don't have the time to help troubleshoot the root cause. You can try getting support upstream. If you're able to find a solution or workaround, please report back here.
