### ISSUE TITLE
Possibility of dropping Ruby 1.8.6 support?

### ISSUE THREAD

**Issue by jacknagel** [Homebrew/linuxbrew#438]
The Homebrew core no longer supports OS X 10.5, so we have little reason to keep our Ruby 1.8.6 compatibility patches around. I'd like to remove them, but I didn't want to commit it without giving fair warning to forks.

I already sent patches to Tigerbrew to move them to different files: https://github.com/mistydemeo/tigerbrew/commit/0695677444b9f90bb53f4a5122a59845a5713161, https://github.com/mistydemeo/tigerbrew/commit/826470a0771cadd07843ebaaa9c11ecf63647e52

What are your feelings about 1.8.6 support in Linuxbrew? Are there many users on distros that don't have a newer Ruby by default?

**Comment by jacknagel** [comment]
Also, we will likely be dropping 1.8.7 support soon after 10.11 is released, as that will mark three OS X releases that ship Ruby 2.0+, and we'd like to start taking advantage of it.

**Comment by sjackman** [comment]
CentOS 5.10, the oldest distro that I make some effort to support, comes with Ruby 1.8.5, so it's already pooched. I don't feel too bad about dropping support for old versions of Ruby. It does make bootstrapping a system a little harder, because you have to install Ruby from source first. In any case, go right ahead. It'll be nice, I imagine, to drop the compatibility patches.

**Comment by jacknagel** [comment]
I've removed them upstream. Thanks!
