### ISSUE TITLE
fish failed to build on Ubuntu Trusty

### ISSUE THREAD

**Issue by puppe** [Homebrew/linuxbrew#482]
fish failed to build with the following message

````
/bin/sh: 1: /usr/bin/sed: not found
````

Output from `brew gist-logs fish`: <https://gist.github.com/anonymous/dc6e97c7c0a309c062b3>

In Ubuntu sed is located at `/bin/sed`, *not* at `/usr/bin/sed`.

Workaround: Edit [line 24 in the fish formula](https://github.com/Homebrew/linuxbrew/blob/cc2c3e50d84201416748a65d5631e1935d476c33/Library/Formula/fish.rb#L24) accordingly.

**Comment by sjackman** [comment]
Does this change work?
```ruby
    system "./configure", "--prefix=#{prefix}", ("SED=/usr/bin/sed" if OS.mac?)
```

**Comment by puppe** [comment]
Yeah, that does the trick.

By the way, thank you very much for your work on linuxbrew! It certainly makes my life easier in the university computer lab.

**Comment by jab** [comment]
Thanks for the quick fix. I'm now able to build and run fish, but when I run `fish -l` I get:
```
ubuntu@localhost ~> Unable to make or open a FIFO for universal variables with path '/run/user/0/fishd.04015e0f4101.notifier': Permission denied
```
Otherwise seems to be working okay so far. Anyone know if I can safely ignore this?

Note: I intentionally did not heed the caveat to add /home/ubuntu/.linuxbrew/bin/fish to /etc/shells as it didn't seem right to add an entry for something inside a user's home directory, especially when the intention is for this user's brew-built fish to be available to this user only. (Assume this user doesn't have root, for instance.) Should this be set up some other way?

**Comment by sjackman** [comment]
I'm afraid I don't know what that error message means. Best to contact the upstream developer.

**Comment by jab** [comment]
Looks like same issue as http://stackoverflow.com/q/27615899 and according to @ridiculousfish (the upstream developer) in http://stackoverflow.com/questions/27615899/fish-error-upon-startup-to-access-a-file-that-does-exist#comment43702109_27615899 it's a misconfiguration issue.
